### ISSUE TITLE
Trying to build on windows

### ISSUE THREAD

**Issue by joglr** [bttger/markdown-flashcards#9]
Hi! This is the perfect project for me, but I am unable to build it using the instructions in the README.

I just installed go v1.22.4 (I've never used go before)

When running the `go build -o mdfc` command in the root of the cloned repository, I get the error:

```
no Go files in C:\Users\jonas\p\markdown-flashcards
```

**Comment by joglr** [comment]
If works if I instead run the build command within the `cmd` directory.

**Comment by bttger** [comment]
Hey, sorry for the late reply. You are right, you need to build from the specific entry point. I will take a look at the issue this weekend.

**Comment by bttger** [comment]
I could not reproduce your error. I've pulled a fresh 1.22.4 go docker container and ran the build without issues:

![image](https://github.com/bttger/markdown-flashcards/assets/49961674/70609273-d71f-49a0-86c8-99cd4347353a)

I will update the last release and add the executables for windows, linux and osx. So you can download it from there if you like :)

**Comment by bttger** [comment]
[Added executables](https://github.com/bttger/markdown-flashcards/releases/tag/v2.0.0) for windows and linux on amd64 platform. Unfortunately, I don't have an ARM machine to build for osx or windows ARM.

**Comment by joglr** [comment]
> I could not reproduce your error. I've pulled a fresh 1.22.4 go docker container and ran the build without issues:
> 
> ![image](https://private-user-images.githubusercontent.com/49961674/340097566-70609273-d71f-49a0-86c8-99cd4347353a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzgyNjUsIm5iZiI6MTcxODYzNzk2NSwicGF0aCI6Ii80OTk2MTY3NC8zNDAwOTc1NjYtNzA2MDkyNzMtZDcxZi00OWEwLTg2YzgtOTljZDQzNDczNTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE1MjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZTNlNjFkZDc0ZTI1ZWZhYTc1MjM2MTRjZjNhZTM3OGJjNGY5NTMzNWMwOGJlYjUxMzhiZTIzMzNjZDQ3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_RjkGCQHbjSY2xCUUob5790eJw2mMy3WE9ly6a96Xg)
> 
> I will update the last release and add the executables for windows, linux and osx. So you can download it from there if you like :)

Thank you, will try it out!
